package com.example.ormlitedemo;

import java.util.Date;

import com.j256.ormlite.field.DatabaseField;

public class Note {
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField
	String subject;
	@DatabaseField
	String text;	
	@DatabaseField
	Date date;

	Note() {
		// needed by ormlite
	}

	public Note(String subject, String text) {
		this.subject = subject;
		this.text = text;
		this.date = new Date(System.currentTimeMillis());
	}

	@Override
	public String toString() {
		return "Note [id=" + id + ", subject=" + subject + ", text="
				+ text + ", date=" + date + "]";
	}
}
